# Generated by Django 2.2.4 on 2020-09-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_tipouser_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='timestamp',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='timeUpdated',
            new_name='dateUpdated',
        ),
        migrations.AddField(
            model_name='tipouser',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipouser',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipouser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
