# Generated by Django 2.2.4 on 2020-09-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200927_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipouser',
            old_name='tipo',
            new_name='nome',
        ),
    ]
