# Generated by Django 2.2.4 on 2020-09-27 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200927_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='followers',
        ),
        migrations.AlterField(
            model_name='followersrelation',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.Perfil'),
        ),
        migrations.AlterField(
            model_name='followersrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipoUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfils', to='users.TipoUser'),
        ),
    ]
