# Generated by Django 2.2.4 on 2020-10-02 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200929_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followersrelation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tipouser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipoUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.TipoUser'),
        ),
        migrations.AlterField(
            model_name='tipouser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatertipoUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
