# Generated by Django 2.2.4 on 2020-11-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201105_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkcredential',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkcredential',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkcredential',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkcredential',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
