# Generated by Django 2.2.4 on 2020-11-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
